# Generated by Django 3.1.8 on 2024-01-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_login_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('password', models.TextField()),
            ],
        ),
    ]
